# Generated by Django 3.2.12 on 2022-08-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=100, null=True)),
                ('tiredIndex', models.CharField(max_length=100)),
                ('userLineId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LineMessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
