# Generated by Django 3.2.12 on 2022-05-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgrecord',
            name='title',
        ),
    ]
