# Generated by Django 3.2.12 on 2022-08-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgwebsite', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
